**13/08/2026** -- Inline descriptive statistics for results section *Fire-related PM2.5 throughout Africa*

Using Hu et al. fire PM2.5 data.

In [1]:
# Sys.setenv(PROJ_DATA = "/home/users/cho00/miniconda3/envs/ppca/share/proj")

In [2]:
library(dplyr)
library(readr)
library(tidyr)
# library(sf)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
SCRATCH_DIR <- Sys.getenv("SCRATCH_DIR")
DATA_PATH   <- file.path(SCRATCH_DIR, 
                         "data/spatial/fire_pm_dep_paper_data",
                         "proc_data/df_af_annual_2000_2023.csv")
# NAT_BOUNDS_PATH     <- file.path(SCRATCH_DIR, 
#                          "data/spatial/nat_boundaries",
#                          "WB_countries_Admin0_10m")
# western_sahara_path <- file.path(SCRATCH_DIR, 
#                          "data/spatial/nat_boundaries",
#                          "western_sahara/gadm41_ESH_0.shp")

In [4]:
df <- read_csv(DATA_PATH)

Rows: 994412 Columns: 74
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (11): geometry, ISO_A3, country, region, continent, INCOME_GRP, ECONOMY,...
dbl (63): lon, lat, total_PM25, total_O3, fire_PM25, fire_O3, fire_PM25_hu, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [5]:
# nat_bounds <- sf::read_sf(NAT_BOUNDS_PATH) |> 
#     filter(CONTINENT == "Africa")

In [6]:
# esh_bounds <- sf::read_sf(western_sahara_path)

##### “Average fire PM2.5 concentrations during 2000-2017 varied from X to Y across Africa (1st-99th percentiles)”

2000-2017:

In [9]:
df |> 
    filter(year <= 2017) |> 
    group_by(lon, lat) |> 
    summarise(
        fire_PM25 = mean(fire_PM25_hu, na.rm = TRUE), 
        .groups = "drop"
    ) |> 
    summarise(
        fire_PM25_min = min(fire_PM25, na.rm = TRUE),
        fire_PM25_p01 = quantile(fire_PM25, 0.01, na.rm = TRUE),
        fire_PM25_p99 = quantile(fire_PM25, 0.99, na.rm = TRUE),
        fire_PM25_max = max(fire_PM25, na.rm = TRUE),
    )

   fire_PM25_min fire_PM25_p01 fire_PM25_p99 fire_PM25_max
1% 0.1680087     0.2947301     17.06127      23.47585

2000-2022:

In [8]:
df |> 
    filter(year <= 2022) |> 
    group_by(lon, lat) |> 
    summarise(
        fire_PM25 = mean(fire_PM25_hu, na.rm = TRUE), 
        .groups = "drop"
    ) |> 
    summarise(
        fire_PM25_min = min(fire_PM25, na.rm = TRUE),
        fire_PM25_p01 = quantile(fire_PM25, 0.01, na.rm = TRUE),
        fire_PM25_p99 = quantile(fire_PM25, 0.99, na.rm = TRUE),
        fire_PM25_max = max(fire_PM25, na.rm = TRUE),
    )

   fire_PM25_min fire_PM25_p01 fire_PM25_p99 fire_PM25_max
1% 0.1700488     0.267224      16.21229      22.07518

##### “Fire PM2.5 accounted for X% of total PM2.5 on average (range: X to Y%, Supplementary Figure S4)”

Note: Hu et al. doesn't provide their estimates of all-source PM -- we will use Xu et al.'s all source and Hu fire-specific PM, and see if looks comparable to the 19% average of Xu et al.

In [26]:
# Create fire frac
df <- df |> 
    mutate(fire_frac_hu = fire_PM25_hu / total_PM25)

2000-2017

In [30]:
# Plain average and range
df |> 
    filter(year <= 2017) |> 
    group_by(lon, lat) |> 
    summarise(
        fire_frac = mean(fire_frac_hu, na.rm = TRUE), 
        .groups = "drop"
    ) |> 
    pull(fire_frac) |>
    summary() * 100

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  0.521   2.251   4.610  11.804  19.210  73.057

In [34]:
# Population-weighted average
df |> 
    filter(year <= 2017) |> 
    group_by(lon, lat) |> 
    summarise(
        fire_frac = mean(fire_frac_hu, na.rm = TRUE), 
        pop_count = mean(pop_count, na.rm = TRUE),
        .groups = "drop"
    ) |> 
    mutate(pw_fire_frac = fire_frac * pop_count) |>
    summarise(
        pw_fire_frac = sum(pw_fire_frac, na.rm = TRUE) / sum(pop_count, na.rm = TRUE)
    ) |>
    pull(pw_fire_frac) * 100

[1] 13.04984

2000-2022 (note this is actually 2000-2019 because Xu et al. all-source PM only goes up to 2019)

In [38]:
# Plain average and range
df |> 
    filter(year <= 2022) |> 
    group_by(lon, lat) |> 
    summarise(
        fire_frac = mean(fire_frac_hu, na.rm = TRUE), 
        .groups = "drop"
    ) |> 
    pull(fire_frac) |>
    summary() * 100

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
 0.5069  2.3166  4.7184 11.5758 18.6829 69.9013    2300

In [36]:
# Population-weighted average
df |> 
    filter(year <= 2022) |> 
    group_by(lon, lat) |> 
    summarise(
        fire_frac = mean(fire_frac_hu, na.rm = TRUE), 
        pop_count = mean(pop_count, na.rm = TRUE),
        .groups = "drop"
    ) |> 
    mutate(pw_fire_frac = fire_frac * pop_count) |>
    summarise(
        pw_fire_frac = sum(pw_fire_frac, na.rm = TRUE) / sum(pop_count, na.rm = TRUE)
    ) |>
    pull(pw_fire_frac) * 100

[1] 12.69591

##### “X% of the continent’s land area had fire PM2.5 concentrations above 5 µg/m3 ... Fire PM2.5 concentrations above 10 µg/m3 and 20 µg/m3 occurred across X% and Y% of land area, respectively”

2000-2017

In [41]:
thresholds <- c(5, 10, 20)

df |> 
    filter(year <= 2017) |>
    group_by(lon, lat) |>
    summarise(
        fire_PM25 = mean(fire_PM25_hu, na.rm = TRUE),
        .groups = "drop"
    ) |> 
    crossing(threshold = thresholds) |>
    group_by(threshold) |> 
    summarise(
        N_grids = n(),
        N_above = sum(fire_PM25 > threshold, na.rm = TRUE),
        N_below = sum(fire_PM25 <= threshold, na.rm = TRUE),
        pct_above = 100 * N_above / N_grids,
        pct_below = 100 * N_below / N_grids,
        .groups = "drop"
    )

  threshold N_grids N_above N_below pct_above  pct_below
1  5        41430   10639   30791   25.6794593 74.32054
2 10        41430    3869   37561    9.3386435 90.66136
3 20        41430      79   41351    0.1906831 99.80932

2000-2022

In [42]:
thresholds <- c(5, 10, 20)

df |> 
    filter(year <= 2022) |>
    group_by(lon, lat) |>
    summarise(
        fire_PM25 = mean(fire_PM25_hu, na.rm = TRUE),
        .groups = "drop"
    ) |> 
    crossing(threshold = thresholds) |>
    group_by(threshold) |> 
    summarise(
        N_grids = n(),
        N_above = sum(fire_PM25 > threshold, na.rm = TRUE),
        N_below = sum(fire_PM25 <= threshold, na.rm = TRUE),
        pct_above = 100 * N_above / N_grids,
        pct_below = 100 * N_below / N_grids,
        .groups = "drop"
    )

  threshold N_grids N_above N_below pct_above   pct_below
1  5        41453   10145   31308   24.47350011 75.52650
2 10        41453    3679   37774    8.87511157 91.12489
3 20        41453      29   41424    0.06995875 99.93004

##### “Population-weighted average concentrations were greatest in central African countries (e.g., Democratic Republic of Congo X µg/m3, Angola Y µg/m3) and lowest in northern African countries (e.g., Morocco X µg/m3, Algeria Y µg/m3) and Cabo Verde (X µg/m3)”

2000-2017:

In [ ]:
pw_avg_fire_PM25_country <- df %>% 
    filter(year <= 2017) %>% 
    mutate(
        pw_fire_PM25 = fire_PM25_hu * pop_count,
        region = recode(region, "Middle Africa" = "Central Africa")
    ) %>% 
    group_by(country, year) %>% 
    summarise(
        region = first(region),
        across( c("pw_fire_PM25", "pop_count"), ~ sum(.x, na.rm = TRUE) ),
        across( c("fire_PM25_hu"), ~ mean(.x, na.rm = TRUE) ),
        .groups = "drop"
    ) %>% 
    mutate(
        pw_avg_fire_PM25 = pw_fire_PM25 / pop_count
    ) %>% 
    mutate(
        pw_avg_fire_PM25_gt_5 = pw_avg_fire_PM25 >= 5 # exceeds WHO 5μgm-3 annual mean guideline
    ) %>% 
    group_by(country) %>% 
    summarise(
        region = first(region),
        pw_avg_fire_PM25 = mean(pw_avg_fire_PM25),
        n_years_gt_5 = sum(pw_avg_fire_PM25_gt_5),
        avg_fire_PM25 = mean(fire_PM25_hu, na.rm = TRUE)    # plain average
    )

In [48]:
pw_avg_fire_PM25_country %>% arrange(desc(pw_avg_fire_PM25))

   country                       region          pw_avg_fire_PM25 n_years_gt_5
1  Congo, Rep. of                Central Africa  13.1959163       18
2  Congo, Democratic Republic of Central Africa  12.1405858       18
3  Angola                        Central Africa  11.2902189       18
4  Central African Republic      Central Africa  11.1589506       18
5  Burundi                       Eastern Africa   9.0671719       18
6  Rwanda                        Eastern Africa   8.3989101       18
7  Zambia                        Eastern Africa   7.1635519       17
8  Gabon                         Central Africa   5.8221839       15
9  Uganda                        Eastern Africa   5.7460985       14
10 South Sudan                   Eastern Africa   5.7123584       15
11 Malawi                        Eastern Africa   5.6757117       12
12 Sierra Leone                  Western Africa   5.3175614       13
13 Guinea                        Western Africa   5.2075282       12
14 Cameroon                      Central Africa   5.0935502       13
15 São Tomé and Príncipe         Central Africa   4.9912192       10
16 Côte d'Ivoire                 Western Africa   4.8791582       10
17 Ghana                         Western Africa   4.7867624        9
18 Namibia                       Southern Africa  4.2714591        3
19 Mozambique                    Eastern Africa   4.1979135        2
20 Togo                          Western Africa   4.1918501        5
21 Equatorial Guinea             Central Africa   4.1460887        2
22 Benin                         Western Africa   4.0041361        4
23 Zimbabwe                      Eastern Africa   3.9911047        1
24 Tanzania                      Eastern Africa   3.7973040        1
25 Guinea-Bissau                 Western Africa   3.7852284        2
26 Liberia                       Western Africa   3.5803605        1
27 Nigeria                       Western Africa   3.2861528        0
28 Chad                          Central Africa   3.1330698        0
29 Madagascar                    Eastern Africa   2.1906143        0
30 Botswana                      Southern Africa  2.1323950        0
31 Ethiopia                      Eastern Africa   2.1024268        0
32 South Africa                  Southern Africa  1.9620011        0
33 Gambia, The                   Western Africa   1.8666890        0
34 eSwatini                      Southern Africa  1.8054215        0
35 Comoros                       Eastern Africa   1.7866485        0
36 Lesotho                       Southern Africa  1.7720280        0
37 Kenya                         Eastern Africa   1.6443147        0
38 Burkina Faso                  Western Africa   1.3764798        0
39 Mali                          Western Africa   1.3373855        0
40 Sudan                         Northern Africa  1.3060038        0
41 Senegal                       Western Africa   1.2436468        0
42 Libya                         Northern Africa  1.1664692        0
43 Egypt, Arab Republic of       Northern Africa  1.0650096        0
44 Eritrea                       Eastern Africa   1.0643696        0
45 Djibouti                      Eastern Africa   0.8712360        0
46 Niger                         Western Africa   0.8665954        0
47 Tunisia                       Northern Africa  0.7952711        0
48 Mauritania                    Western Africa   0.7102188        0
49 Algeria                       Northern Africa  0.5258076        0
50 Morocco                       Northern Africa  0.3635477        0
51 Somalia                       Eastern Africa   0.3465598        0
52 Cabo Verde                    Western Africa   0.3279186        0
   avg_fire_PM25
1   9.8002865
2  11.9390991
3  11.0704478
4  10.4227674
5   9.0079043
6   8.1526627
7   7.7587551
8   6.0001367
9   5.6617374
10  6.0909170
11  5.7341791
12  5.2528055
13  5.4012607
14  6.6157425
15  4.9767996
16  4.8874731
17  4.6652584
18  2.9236041
19  4.4596491
20  4.5923326
21  4.1889541
22  3.5998689
23  3.5758931
24  4.5218996
25  3.6939624
26  3.4058677
27  2.8325258
28  1.8429056
29  2.4709779
30  2.4217696
31  1.8411350
32  1.3883546
33  2.0708965
34  1.7786976
35  1.8461133
36  1.7766579
37  1.1585847
38  1.4558963
39  0.9877657
40  1.2550494
41  1.7902237
42  1.3254721
43  1.1683827
44  1.2185338
45  0.9530556
46  0.8731677
47  0.9144476
48  0.6021962
49  0.8065509
50  0.4350570
51  0.3646574
52  0.3473965

##### “In X of the 52 countries, population-weighted annual average fire PM2.5 concentrations alone exceeded the WHO air quality guideline threshold for total PM2.5 in every year between 2000 and 2017”

In [87]:
# No. of countries where annual mean fire PM2.5 exceeds 5μgm-3 every year for 2000-2017
pw_avg_fire_PM25_country %>%
    count(n_years_gt_5 == 18)  # all 18 years

  n_years_gt_5 == 18 n
1 FALSE              46
2  TRUE               6

2000-2022:

In [11]:
pw_avg_fire_PM25_country <- df %>% 
    filter(year <= 2022) %>% 
    mutate(
        pw_fire_PM25 = fire_PM25_hu * pop_count,
        region = recode(region, "Middle Africa" = "Central Africa")
    ) %>% 
    group_by(country, year) %>% 
    summarise(
        region = first(region),
        across( c("pw_fire_PM25", "pop_count"), ~ sum(.x, na.rm = TRUE) ),
        across( c("fire_PM25_hu"), ~ mean(.x, na.rm = TRUE) ),
        .groups = "drop"
    ) %>% 
    mutate(
        pw_avg_fire_PM25 = pw_fire_PM25 / pop_count
    ) %>% 
    mutate(
        pw_avg_fire_PM25_gt_5 = pw_avg_fire_PM25 >= 5 # exceeds WHO 5μgm-3 annual mean guideline
    ) %>% 
    group_by(country) %>% 
    summarise(
        region = first(region),
        pw_avg_fire_PM25 = mean(pw_avg_fire_PM25),
        n_years_gt_5 = sum(pw_avg_fire_PM25_gt_5),
        avg_fire_PM25 = mean(fire_PM25_hu, na.rm = TRUE)    # plain average
    )

In [12]:
pw_avg_fire_PM25_country %>% arrange(desc(pw_avg_fire_PM25))

   country                       region          pw_avg_fire_PM25 n_years_gt_5
1  Congo, Rep. of                Central Africa  12.0909188       23
2  Congo, Democratic Republic of Central Africa  11.6297472       23
3  Central African Republic      Central Africa  10.9394975       23
4  Angola                        Central Africa  10.5263460       23
5  Burundi                       Eastern Africa   8.5486191       22
6  Rwanda                        Eastern Africa   7.7693154       22
7  Zambia                        Eastern Africa   6.9120039       20
8  Gabon                         Central Africa   5.8343411       19
9  Uganda                        Eastern Africa   5.5959484       16
10 South Sudan                   Eastern Africa   5.5338271       17
11 Malawi                        Eastern Africa   5.4568709       14
12 São Tomé and Príncipe         Central Africa   5.4117883       12
13 Sierra Leone                  Western Africa   4.8761552       13
14 Cameroon                      Central Africa   4.8545229       13
15 Guinea                        Western Africa   4.8299603       12
16 Côte d'Ivoire                 Western Africa   4.4623705       10
17 Ghana                         Western Africa   4.4231329        9
18 Equatorial Guinea             Central Africa   4.1215291        3
19 Namibia                       Southern Africa  4.0346328        3
20 Mozambique                    Eastern Africa   3.9984009        2
21 Togo                          Western Africa   3.8253334        5
22 Zimbabwe                      Eastern Africa   3.8104129        1
23 Benin                         Western Africa   3.6437027        4
24 Tanzania                      Eastern Africa   3.6369166        1
25 Guinea-Bissau                 Western Africa   3.4468320        2
26 Liberia                       Western Africa   3.4343135        1
27 Nigeria                       Western Africa   3.0517783        0
28 Chad                          Central Africa   3.0091241        0
29 Madagascar                    Eastern Africa   2.1067804        0
30 Botswana                      Southern Africa  1.9774884        0
31 Ethiopia                      Eastern Africa   1.9144543        0
32 South Africa                  Southern Africa  1.8388481        0
33 Gambia, The                   Western Africa   1.7263522        0
34 eSwatini                      Southern Africa  1.6786005        0
35 Comoros                       Eastern Africa   1.6649733        0
36 Lesotho                       Southern Africa  1.6516011        0
37 Kenya                         Eastern Africa   1.5719649        0
38 Burkina Faso                  Western Africa   1.2721738        0
39 Mali                          Western Africa   1.2572760        0
40 Sudan                         Northern Africa  1.1984926        0
41 Senegal                       Western Africa   1.1596801        0
42 Libya                         Northern Africa  1.0540142        0
43 Eritrea                       Eastern Africa   0.9578052        0
44 Egypt, Arab Republic of       Northern Africa  0.9387856        0
45 Niger                         Western Africa   0.7961244        0
46 Djibouti                      Eastern Africa   0.7866617        0
47 Tunisia                       Northern Africa  0.7098689        0
48 Mauritania                    Western Africa   0.6559138        0
49 Algeria                       Northern Africa  0.4775633        0
50 Morocco                       Northern Africa  0.3223509        0
51 Somalia                       Eastern Africa   0.3173869        0
52 Cabo Verde                    Western Africa   0.2921648        0
   avg_fire_PM25
1   9.5579475
2  11.6486025
3  10.2146685
4  10.6107114
5   8.4580711
6   7.5543012
7   7.5825917
8   6.0152648
9   5.4711407
10  5.9203825
11  5.4919942
12  5.3050862
13  4.8609323
14  6.3828361
15  5.0245975
16  4.4591335
17  4.3015793
18  4.2229972
19  2.8120030
20  4.3082628
21  4.1483803
22  3.3990652
23  3.2448380
24  4.3869748
25  3.3773999
26  3.2800369
27  2.6231575
28  1.7644366
29  2.3683436
30  2.2649797
31  1.7023282
32  1.3049906
33  1.9299056
34  1.6543454
35  1.8072117
36  1.6573781
37  1.0876385
38  1.3409936
39  0.9260802
40  1.1784760
41  1.6746390
42  1.2692032
43  1.1148209
44  1.1098369
45  0.8159869
46  0.8680951
47  0.8446363
48  0.5647150
49  0.7711621
50  0.3975884
51  0.3367601
52  0.3130496

In [14]:
# No. countries w/ avg over 5:
print(nrow(pw_avg_fire_PM25_country |> filter(pw_avg_fire_PM25 > 5)))
pw_avg_fire_PM25_country |> filter(pw_avg_fire_PM25 > 5)

[1] 12

   country                       region         pw_avg_fire_PM25 n_years_gt_5
1  Angola                        Central Africa 10.526346        23
2  Burundi                       Eastern Africa  8.548619        22
3  Central African Republic      Central Africa 10.939498        23
4  Congo, Democratic Republic of Central Africa 11.629747        23
5  Congo, Rep. of                Central Africa 12.090919        23
6  Gabon                         Central Africa  5.834341        19
7  Malawi                        Eastern Africa  5.456871        14
8  Rwanda                        Eastern Africa  7.769315        22
9  South Sudan                   Eastern Africa  5.533827        17
10 São Tomé and Príncipe         Central Africa  5.411788        12
11 Uganda                        Eastern Africa  5.595948        16
12 Zambia                        Eastern Africa  6.912004        20
   avg_fire_PM25
1  10.610711
2   8.458071
3  10.214669
4  11.648602
5   9.557948
6   6.015265
7   5.491994
8   7.554301
9   5.920382
10  5.305086
11  5.471141
12  7.582592

##### “In X of the 52 countries, population-weighted annual average fire PM2.5 concentrations alone exceeded the WHO air quality guideline threshold for total PM2.5 in every year between 2000 and 2022"

In [91]:
# No. of countries where annual mean fire PM2.5 exceeds 5μgm-3 every year for 2000-2022
pw_avg_fire_PM25_country %>%
    count(n_years_gt_5 == 23)  # all 23 years

  n_years_gt_5 == 23 n
1 FALSE              48
2  TRUE               4

##### “Population-weighted fire PM2.5 concentrations were higher in rural areas (X µg/m3) than urban (Y µg/m3)”

2000-2017:

In [94]:
df |> 
    filter(year <= 2017) |> 
    filter(!is.na(urban_rural_cat)) |> 
    mutate(
        pw_fire_PM25 = fire_PM25_hu * pop_count,
    ) |> 
    group_by(urban_rural_cat, year) |> 
    summarise(
        across( c("pw_fire_PM25", "pop_count"), ~ sum(.x, na.rm = TRUE) ),
        .groups = "drop"
    ) |> 
    mutate(
        pw_avg_fire_PM25 = pw_fire_PM25 / pop_count
    ) |> 
    group_by(urban_rural_cat) |> 
    summarise(
        pw_avg_fire_PM25 = mean(pw_avg_fire_PM25),
        .groups = "drop"
    )

  urban_rural_cat pw_avg_fire_PM25
1 rural           4.060461
2 urban           3.122631

2000-2022:

In [95]:
df |> 
    filter(year <= 2022) |> 
    filter(!is.na(urban_rural_cat)) |> 
    mutate(
        pw_fire_PM25 = fire_PM25_hu * pop_count,
    ) |> 
    group_by(urban_rural_cat, year) |> 
    summarise(
        across( c("pw_fire_PM25", "pop_count"), ~ sum(.x, na.rm = TRUE) ),
        .groups = "drop"
    ) |> 
    mutate(
        pw_avg_fire_PM25 = pw_fire_PM25 / pop_count
    ) |> 
    group_by(urban_rural_cat) |> 
    summarise(
        pw_avg_fire_PM25 = mean(pw_avg_fire_PM25),
        .groups = "drop"
    )

  urban_rural_cat pw_avg_fire_PM25
1 rural           3.849481
2 urban           2.992364

##### “Rural areas had higher fire PM2.5 than urban areas in X out of 48 countries.”

2000-2017

In [122]:
# Population-weighted average fire PM2.5 by country and urban/rural category
pw_avg_fire_PM25_country_ur <- df %>%
    filter(year <= 2017) %>% 
    filter(!is.na(urban_rural_cat)) %>%
    mutate(
        pw_fire_PM25 = fire_PM25_hu * pop_count,
    ) %>% 
    group_by(country, year, urban_rural_cat) %>% 
    summarise(
        across( c("pw_fire_PM25", "pop_count"), ~ sum(.x, na.rm = TRUE) ),
        across( c("fire_PM25_hu"), ~ mean(.x, na.rm = TRUE) ),
        .groups = "drop"
    ) %>% 
    mutate(
        pw_avg_fire_PM25 = pw_fire_PM25 / pop_count
    ) %>% 
    group_by(country, urban_rural_cat) %>% 
    summarise(
        pw_avg_fire_PM25 = mean(pw_avg_fire_PM25),
        avg_fire_PM25 = mean(fire_PM25_hu, na.rm = TRUE),   # plain average
        .groups = "drop"
    )

In [123]:
# Pivot to wide-form
pw_avg_fire_PM25_country_ur_wide <- pw_avg_fire_PM25_country_ur %>% 
    pivot_wider(
        id_cols = c("country"),
        names_from = "urban_rural_cat",
        values_from = "pw_avg_fire_PM25",
        names_prefix = "pw_avg_fire_PM25_"
    ) %>% 
    mutate(rural_gt_urban = pw_avg_fire_PM25_rural > pw_avg_fire_PM25_urban)
pw_avg_fire_PM25_country_ur_wide

   country                       pw_avg_fire_PM25_rural pw_avg_fire_PM25_urban
1  Algeria                        0.5149474              0.5383062
2  Angola                        11.6718375              9.6000327
3  Benin                          3.9765453              4.0782330
4  Botswana                       2.1556832              2.0144284
5  Burkina Faso                   1.4001448              1.2004735
6  Burundi                        8.8239720              9.8796821
7  Cabo Verde                     0.3453503              0.2928691
8  Cameroon                       5.1654428              4.8258400
9  Central African Republic      11.0709651             11.4967801
10 Chad                           3.2320824              1.1706672
11 Comoros                        1.7866485                     NA
12 Congo, Democratic Republic of 12.0621661             12.4555902
13 Congo, Rep. of                 9.6748855             14.7130220
14 Côte d'Ivoire                  4.9948613              4.5742238
15 Djibouti                       0.9106557              0.8496255
16 Egypt, Arab Republic of        1.0787290              1.0649010
17 Equatorial Guinea              4.1460887                     NA
18 Eritrea                        1.0766276              0.9664665
19 Ethiopia                       2.1339069              1.9243113
20 Gabon                          6.1980671              5.0550634
21 Gambia, The                    2.0289129              1.5468080
22 Ghana                          4.7216310              4.9201556
23 Guinea                         5.3503290              4.7266378
24 Guinea-Bissau                  3.8859745              3.5457245
25 Kenya                          1.4803001              1.7506002
26 Lesotho                        1.7720280                     NA
27 Liberia                        3.5865536              3.5662653
28 Libya                          1.1350344              1.2068853
29 Madagascar                     2.2473032              1.8804050
30 Malawi                         5.3907789              6.3808257
31 Mali                           1.2793992              1.5249813
32 Mauritania                     0.7726515              0.5476208
33 Morocco                        0.3670958              0.3614739
34 Mozambique                     4.4628766              3.0305469
35 Namibia                        4.9354695              3.0463013
36 Niger                          0.8591490              0.9680628
37 Nigeria                        2.9143032              4.0544083
38 Rwanda                         7.4973861              8.7201405
39 Senegal                        1.4246036              0.6911052
40 Sierra Leone                   5.3119511              5.3264051
41 Somalia                        0.3459028              0.3343292
42 South Africa                   1.5882882              2.0727466
43 South Sudan                    5.7123584                     NA
44 Sudan                          1.3264199              1.1211605
45 São Tomé and Príncipe          4.3947281              5.2411621
46 Tanzania                       4.1518835              2.7158895
47 Togo                           4.3094283              3.8532968
48 Tunisia                        0.7618929              0.8308026
49 Uganda                         5.9371864              5.3807498
50 Zambia                         7.3809520              6.4196716
51 Zimbabwe                       3.7675772              4.6039681
52 eSwatini                       1.7991607              1.8075441
   rural_gt_urban
1  FALSE
2   TRUE
3  FALSE
4   TRUE
5   TRUE
6  FALSE
7   TRUE
8   TRUE
9  FALSE
10  TRUE
11    NA
12 FALSE
13 FALSE
14  TRUE
15  TRUE
16  TRUE
17    NA
18  TRUE
19  TRUE
20  TRUE
21  TRUE
22 FALSE
23  TRUE
24  TRUE
25 FALSE
26    NA
27  TRUE
28 FALSE
29  TRUE
30 FALSE
31 FALSE
32  TRUE
33  TRUE
34  TRUE
35  TRUE
36 FALSE
37 FALSE
38 FALSE
39  TRUE
40 FALSE
41  TRUE
42 FALSE
43    NA
44  TRUE
45 FALSE
46  TRUE
47  TRUE
48 FALSE
49  TRUE
50  TRUE
51 FALSE
52 FALSE

In [124]:
# Countries where rural fire PM2.5 exceeds urban fire PM2.5
pw_avg_fire_PM25_country_ur_wide |> count(rural_gt_urban)

  rural_gt_urban n
1 FALSE          20
2  TRUE          28
3    NA           4

In [125]:
# Countries where urban fire PM2.5 exceeds rural fire PM2.5
pw_avg_fire_PM25_country_ur_wide |> filter(!rural_gt_urban)

   country                       pw_avg_fire_PM25_rural pw_avg_fire_PM25_urban
1  Algeria                        0.5149474              0.5383062
2  Benin                          3.9765453              4.0782330
3  Burundi                        8.8239720              9.8796821
4  Central African Republic      11.0709651             11.4967801
5  Congo, Democratic Republic of 12.0621661             12.4555902
6  Congo, Rep. of                 9.6748855             14.7130220
7  Ghana                          4.7216310              4.9201556
8  Kenya                          1.4803001              1.7506002
9  Libya                          1.1350344              1.2068853
10 Malawi                         5.3907789              6.3808257
11 Mali                           1.2793992              1.5249813
12 Niger                          0.8591490              0.9680628
13 Nigeria                        2.9143032              4.0544083
14 Rwanda                         7.4973861              8.7201405
15 Sierra Leone                   5.3119511              5.3264051
16 South Africa                   1.5882882              2.0727466
17 São Tomé and Príncipe          4.3947281              5.2411621
18 Tunisia                        0.7618929              0.8308026
19 Zimbabwe                       3.7675772              4.6039681
20 eSwatini                       1.7991607              1.8075441
   rural_gt_urban
1  FALSE
2  FALSE
3  FALSE
4  FALSE
5  FALSE
6  FALSE
7  FALSE
8  FALSE
9  FALSE
10 FALSE
11 FALSE
12 FALSE
13 FALSE
14 FALSE
15 FALSE
16 FALSE
17 FALSE
18 FALSE
19 FALSE
20 FALSE

2000-2022:

In [135]:
# Population-weighted average fire PM2.5 by country and urban/rural category
pw_avg_fire_PM25_country_ur <- df %>%
    filter(year <= 2022) %>% 
    filter(!is.na(urban_rural_cat)) %>%
    mutate(
        pw_fire_PM25 = fire_PM25_hu * pop_count,
    ) %>% 
    group_by(country, year, urban_rural_cat) %>% 
    summarise(
        across( c("pw_fire_PM25", "pop_count"), ~ sum(.x, na.rm = TRUE) ),
        across( c("fire_PM25_hu"), ~ mean(.x, na.rm = TRUE) ),
        .groups = "drop"
    ) %>% 
    mutate(
        pw_avg_fire_PM25 = pw_fire_PM25 / pop_count
    ) %>% 
    group_by(country, urban_rural_cat) %>% 
    summarise(
        pw_avg_fire_PM25    = mean(pw_avg_fire_PM25),
        avg_fire_PM25       = mean(fire_PM25_hu, na.rm = TRUE),   # plain average
        n_years_averaged    = n(),
        .groups = "drop"
    )

In [138]:
# Comoros, Equatorial Guinea, Lesotho, South Sudan have 2 years of 'urban' grid cells
# with the second-generation WorldPop data
pw_avg_fire_PM25_country_ur |> filter(n_years_averaged < 23)

  country           urban_rural_cat pw_avg_fire_PM25 avg_fire_PM25
1 Comoros           urban           0.6263113        0.6263113
2 Equatorial Guinea urban           4.2320536        4.2500895
3 Lesotho           urban           0.7070847        0.7070847
4 South Sudan       urban           6.7947409        7.1000819
5 eSwatini          urban           1.5892183        1.5892183
  n_years_averaged
1  2
2  2
3  2
4  2
5 11

In [140]:
# Pivot to wide-form
pw_avg_fire_PM25_country_ur_wide <- pw_avg_fire_PM25_country_ur %>% 
    pivot_wider(
        id_cols = c("country"),
        names_from = "urban_rural_cat",
        values_from = "pw_avg_fire_PM25",
        names_prefix = "pw_avg_fire_PM25_"
    ) %>% 
    mutate(rural_gt_urban = pw_avg_fire_PM25_rural > pw_avg_fire_PM25_urban)
pw_avg_fire_PM25_country_ur_wide

   country                       pw_avg_fire_PM25_rural pw_avg_fire_PM25_urban
1  Algeria                        0.4738842              0.4855039
2  Angola                        10.9368097              9.1060848
3  Benin                          3.5752921              3.7518145
4  Botswana                       2.0101499              1.8575519
5  Burkina Faso                   1.2930129              1.1253229
6  Burundi                        8.2431155              9.2200840
7  Cabo Verde                     0.3081674              0.2610138
8  Cameroon                       4.9085052              4.6614496
9  Central African Republic      10.7923386             11.4606959
10 Chad                           3.1058324              1.2699435
11 Comoros                        1.6840215              0.6263113
12 Congo, Democratic Republic of 11.6823032             11.6524484
13 Congo, Rep. of                 9.4356542             13.2648274
14 Côte d'Ivoire                  4.5290353              4.2501471
15 Djibouti                       0.8321380              0.7600622
16 Egypt, Arab Republic of        0.9976463              0.9374018
17 Equatorial Guinea              4.1840118              4.2320536
18 Eritrea                        0.9738919              0.8363319
19 Ethiopia                       1.9646995              1.7139120
20 Gabon                          6.2137657              5.1024490
21 Gambia, The                    1.9024517              1.4220696
22 Ghana                          4.3396395              4.5487494
23 Guinea                         4.9718055              4.3866862
24 Guinea-Bissau                  3.5259293              3.2591843
25 Kenya                          1.3391109              1.6924964
26 Lesotho                        1.6518015              0.7070847
27 Liberia                        3.4244266              3.4317318
28 Libya                          1.0434694              1.0686177
29 Madagascar                     2.1529447              1.8535304
30 Malawi                         5.1425062              6.1093852
31 Mali                           1.1902573              1.4381126
32 Mauritania                     0.7126847              0.5131704
33 Morocco                        0.3269016              0.3204705
34 Mozambique                     4.2556459              2.9518498
35 Namibia                        4.6382939              2.9472486
36 Niger                          0.7890661              0.8855594
37 Nigeria                        2.6514917              3.7439924
38 Rwanda                         6.7045707              8.0416783
39 Senegal                        1.3429735              0.6624883
40 Sierra Leone                   4.8891345              4.8519270
41 Somalia                        0.3171193              0.2999498
42 South Africa                   1.4872920              1.9427266
43 South Sudan                    5.5280435              6.7947409
44 Sudan                          1.2258515              1.0332874
45 São Tomé and Príncipe          4.5457221              5.7051130
46 Tanzania                       3.9732773              2.6777176
47 Togo                           3.9070641              3.5840377
48 Tunisia                        0.6844334              0.7373711
49 Uganda                         5.7824159              5.2839543
50 Zambia                         7.1163760              6.2518863
51 Zimbabwe                       3.5946517              4.3748529
52 eSwatini                       1.6694797              1.5892183
   rural_gt_urban
1  FALSE
2   TRUE
3  FALSE
4   TRUE
5   TRUE
6  FALSE
7   TRUE
8   TRUE
9  FALSE
10  TRUE
11  TRUE
12  TRUE
13 FALSE
14  TRUE
15  TRUE
16  TRUE
17 FALSE
18  TRUE
19  TRUE
20  TRUE
21  TRUE
22 FALSE
23  TRUE
24  TRUE
25 FALSE
26  TRUE
27 FALSE
28 FALSE
29  TRUE
30 FALSE
31 FALSE
32  TRUE
33  TRUE
34  TRUE
35  TRUE
36 FALSE
37 FALSE
38 FALSE
39  TRUE
40  TRUE
41  TRUE
42 FALSE
43 FALSE
44  TRUE
45 FALSE
46  TRUE
47  TRUE
48 FALSE
49  TRUE
50  TRUE
51 FALSE
52  TRUE

In [128]:
# Countries where rural fire PM2.5 exceeds urban fire PM2.5
pw_avg_fire_PM25_country_ur_wide |> count(rural_gt_urban)

  rural_gt_urban n
1 FALSE          20
2  TRUE          32

In [139]:
# Countries where urban fire PM2.5 exceeds rural fire PM2.5
pw_avg_fire_PM25_country_ur_wide |> filter(!rural_gt_urban)

   country                  pw_avg_fire_PM25_rural pw_avg_fire_PM25_urban
1  Algeria                   0.4738842              0.4855039
2  Benin                     3.5752921              3.7518145
3  Burundi                   8.2431155              9.2200840
4  Central African Republic 10.7923386             11.4606959
5  Congo, Rep. of            9.4356542             13.2648274
6  Equatorial Guinea         4.1840118              4.2320536
7  Ghana                     4.3396395              4.5487494
8  Kenya                     1.3391109              1.6924964
9  Liberia                   3.4244266              3.4317318
10 Libya                     1.0434694              1.0686177
11 Malawi                    5.1425062              6.1093852
12 Mali                      1.1902573              1.4381126
13 Niger                     0.7890661              0.8855594
14 Nigeria                   2.6514917              3.7439924
15 Rwanda                    6.7045707              8.0416783
16 South Africa              1.4872920              1.9427266
17 South Sudan               5.5280435              6.7947409
18 São Tomé and Príncipe     4.5457221              5.7051130
19 Tunisia                   0.6844334              0.7373711
20 Zimbabwe                  3.5946517              4.3748529
   rural_gt_urban
1  FALSE
2  FALSE
3  FALSE
4  FALSE
5  FALSE
6  FALSE
7  FALSE
8  FALSE
9  FALSE
10 FALSE
11 FALSE
12 FALSE
13 FALSE
14 FALSE
15 FALSE
16 FALSE
17 FALSE
18 FALSE
19 FALSE
20 FALSE